---
version: "2.1"
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=501
      - PGID=20
      - MYSQL_ROOT_PASSWORD=Password123
      - TZ=Europe/London
    volumes:
      - ./database:/config
    ports:
      - 4306:3306
    restart: unless-stopped

  baseball:
    build:
      context: .
      dockerfile: dockerfile
    image: baseball
    volumes:
      - ./baseball.sql:/App/baseball.sql
    command: sleep 9999999
    restart: unless-stopped
